BUG: Update CTK to fix Visual DICOM Browser
Contains these CTK fixes and improvements:

Revision: 7ed1da357b9e7e2462b4b764882612484c6fa051
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-24 1:33:32 PM
Message:
BUG: Do not overwrite the full palette in ctkDICOMServerNodeWidget2

Revision: afec0d3bd264f2644a6912810736ff6de8c51992
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-22 7:34:49 AM
Message:
ENH: Clean trusted servers API and GUI
BUG: Fix colors for the settings in dark mode

Revision: 55bdc75f38b9ae78f524f07c9af6ba66140a0c77
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-22 4:43:25 AM
Message:
BUG: Fix filtering date condition in DIMSE query

Revision: 518c93cc40b866a3635de1d16aebfb94ce0b916a
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-16 3:01:50 PM
Message:
BUG: Fix filtering for ctkDICOMQuery

Revision: 435c1f214a80eced4b499133162450371a5c46bb
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-16 1:17:22 PM
Message:
BUG: Resolve exception in getDICOMCenterFrameFromInstances for absent metadata

Revision: 4ef31c584ef0f7580bcb82876ce754f508f2b871
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-16 8:54:40 AM
Message:
BUG: Fix visual dicom browser tests

Revision: f752bbad8e93d477ea21b51283fe91057f9959b4
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-16 8:41:19 AM
Message:
ENH: Add trusted property to ctkDICOMServer

Revision: 037fca7425a9b96a53be5776b263d42dc7b1eaa6
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-16 8:12:23 AM
Message:
STYLE: Clean set/get methods and allow/deny servers API
Co-authored-by: Andras Lasso <lasso@queensu.ca>

Revision: 22009d6e9a7d22376434e3b2f26693aad474beb2
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-15 7:33:34 AM
Message:
BUG: Import folder shpuld not reset filters

Revision: 2593d240ef7671e9ccf5e2a57df6c856c393fa94
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-09 7:50:56 AM
Message:
STYLE: Set prefered vertical size policy to SearchMenuButton

Revision: df798a5f17f0b1f38d4c32c2db5374fb06a4f215
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-08 7:28:44 AM
Message:
ENH: Use json design in the dicom database for storing connections

Revision: 067a9e7855ad52361d98b53dc59f031cb509f0fd
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-08 4:33:59 AM
Message:
STYLE: Replace QMutex with QMutexLocker in the ctkJobScheduler
STYLE: Fix indentation for visual dicom browser classes
STYLE: Fix doxygen for visual dicom browser classes

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Co-authored-by: Andras Lasso <lasso@queensu.ca>

Revision: 40ed50401c2fba45ca664d5b07ed6c9e1e23ef3c
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-04 5:54:22 PM
Message:
ENH: Add UI to filter enabled servers on patient basis
ENH: Use menu button to disbale query/retrieve for search

Revision: 6ddb9919aeb5ec039e54d451bfe0d96faeadc0fb
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-04 8:42:30 AM
Message:
ENH: Add connectionNames table to ctkDICOMDatabase

Revision: fe3b71108881b069db48d9dee55deff501c7e8e8
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-03 10:33:41 AM
Message:
BUG: Fix minimum value for the progress bar UI in the ctkDICOMJobListWidget

Revision: 13ab9eaa3d27903e2083404672345f120852f6b1
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-03 10:28:37 AM
Message:
ENH: Add log error when a patient has missing PatientsName/PatientID.

Revision: 07dc2ee6385e877e85bf1f2701e36d2ca7362ccd
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-03 10:14:53 AM
Message:
BUG: Fix release association when canceling operations for the scheduler

Revision: d0c6f3cbfad2c58db93211de1a852e0a5c73d2db
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-02 11:55:23 AM
Message:
BUG: Fix import for multiple folders for the visual DICOM browser

Revision: 0cd3829e3fbb4987f227066eab57b133df2e4106
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-02 11:03:50 AM
Message:
ENH: Add previous/next patient (Ctrl-tab/Ctrl-shift-tab) shortcuts

Revision: 6c6ef37973768337039e3e8e504bc87a4828b9d7
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-02 8:31:41 AM
Message:
BUG: Fix the insertPatient method not using uids from uidsForDataSet method

Revision: 620e6bb64283678c43c676e9ce5fd84dbd012441
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-02 7:47:00 AM
Message:
ENH: Patient selection has to be kept when querying the visual DICOM browser

Revision: 9be0514644f24492ff7ed7f12ec88279ed3da5b8
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-02 7:10:19 AM
Message:
ENH: Hitting enter in a search field should run the query

Revision: eb04feeab5252324feb90b7d9637fef57bd4c51d
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-04-02 6:44:11 AM
Message:
ENH: Wrap DCMTK abort and release SCU method to make them thread-safe

Revision: b1b2bc0c2182ecf3fdbbdc0d84d7ad1735fa4beb
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-03-25 6:49:55 AM
Message:
STYLE: Group Settings and Jobs UI groupboxes into Advanced
STYLE: Add splitter in the visual DICOM browser between patient tab navigation widget and Advanced group box
STYLE: Add retrieve string to protocol and proxy column names in the ctkDICOMServerNodeWidget2
BUG: Preserve row selection after clicking Apply changes in the ctkDICOMServerNodeWidget2
ENH: Make server settings human readeable in the qt settings file for the ctkDICOMServerNodeWidget2
ENH: Highlight in dark yellow the modified fields in the ctkDICOMServerNodeWidget2
ENH: Improve verify server. Added job and worker classes for running it in background. Added verification status column in the ctkDICOMServerNodeWidget2
BUG: Fix selection color when items are modified in the table in the ctkDICOMServerNodeWidget2
ENH: Call onShowPatients for ctkDICOMVisualBrowserWidget in the visual DICOM browser application
BUG: Fix jobs cleaning in the ctkJobScheduler destructor
ENH: Verify server, in the ctkDICOMServerNodeWidget2, should verify the current modified server settings
BUG: Verification column in the ctkDICOMServerNodeWidget2 should be updated only from jobs which started after clicking the verify button.

Revision: e5970bc87c6a9f77b901ece5889b4455259d6620
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date: 2024-04-02 5:20:39 PM
Message:
ENH: Update GitHub workflow to test build against Qt 5.12.8

This update to the GitHub workflow enables testing builds against Qt 5.12.8
on Ubuntu 20.04. Notably, the build excludes VTK due to unavailability of
VTK 9 packages on Ubuntu 20.04.

To support building ctkDICOMCore on Ubuntu 20.04, DCMTK is now built from source
using the CTK SuperBuild. This decision stems from the absence of DCMTK 3.6.6, as
indicated by the DCMTK package version 3.6.4 available[^1] via apt-get. The need for
building DCMTK from source arises from the utilization of the function
`DcmSCP::acceptAssociations`, introduced in DCMTK 3.6.6
through DCMTK/dcmtk@c3d4c8e09 (Added alternative service provision API to DcmSCP).

Additionally, to ensure completion of the independent GitHub CI build workflows
testing against Qt 5.15.2 and Qt 5.12.8, the "fail-fast" option is set to false.

[^1]: https://packages.ubuntu.com/focal/dcmtk

Revision: eaaabf65e40b71ba198b21132fede83839603832
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date: 2024-04-03 12:35:58 AM
Message:
DOC: Update README to reference GitHub Actions status badge

Revision: 9e6f70c4e42e5004415a1ff7eea15911594b22f2
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date: 2024-04-02 5:50:37 PM
Message:
COMP: Ensure DICOMWidget compatibility with Qt 5.12.8

This commit resolves compilation issues encountered when building the DICOMWidget
against Qt 5.12.8. The changes include:

1. Removed the setting of the unsupported and unused `placeholderText` property
   from `ctkDICOMVisualBrowserWidget.ui`. This property's removal does not affect
   widget rendering. The removal addresses a compilation error introduced in commit
   88ff72b9 ("ENH: Add Visual DICOM Browser (#1165)", 2024-01-19):

    ```
    /path/to/CTK/Libs/DICOM/Core/ctkDICOMStorageListener.cpp:71:18: error: ‘acceptAssociations’ is not a member of ‘DcmSCP’
       71 |   return DcmSCP::acceptAssociations();
          |                  ^~~~~~~~~~~~~~~~~~
    ```

2. Introduced conditional utilization of `Qt::MatchRegularExpression`, available
   in Qt 5.15, to resolve a compilation error introduced in
   commit 888cdd92 ("ENH: Add ctkDICOMJobListWidget for logging jobs activity in the UI", 2024-01-18):

    ```
    /path/to/CTK/Libs/DICOM/Widgets/ctkDICOMJobListWidget.cpp:405:69: error: ‘MatchRegularExpression’ is not a member of ‘Qt’
    405 |   QList<QStandardItem*> list = this->findItems(tr("completed"), Qt::MatchRegularExpression, Columns::Status);
        |                                                                     ^~~~~~~~~~~~~~~~~~~~~~
    ```

Revision: 867f3875dcf93071661c8678fad30b1bd05ad498
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date: 2024-04-02 3:11:41 PM
Message:
ENH: Switch from CircleCI to GitHub Action for building CTK

Streamline the build process by eliminating reliance on the
`slicer/buildenv-qt5-centos7:latest` Docker image in favor of direct
host-based builds. Python, Qt, VTK, and DCMTK are now installed directly
on the host system.

Build on ubuntu-latest (22.04) installs Qt 5.15.2